export const LOAD_CUSTOMERS = "LOAD_CUSTOMERS";
export const LOAD_SEL_CUSTOMER = "LOAD_SEL_CUSTOMER";
export const CLEAR_SEL_CUSTOMER = "CLEAR_SEL_CUSTOMER"
export const UPDATE_CUSTOMERS = "UPDATE_CUSTOMERS";
export const UPDATE_SEL_CUSTOMER = "UPDATE_SEL_CUSTOMER";