export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOAD_SEL_PRODUCTS = "LOAD_SEL_PRODUCTS";
export const CLEAR_SEL_PRODUCTS = "CLEAR_SEL_PRODUCTS"
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_SEL_PRODUCTS = "UPDATE_SEL_PRODUCTS";
export const LOAD_GS_DATA = "LOAD_GS_DATA";